AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  TEst template

Parameters:
  DomainNameString:
    Description: The domain name
    Type: String
    Default: whatwoulddododo.com
Globals:
  Function:
    Timeout: 18
    Runtime: nodejs8.10
    Handler: index.handler
Resources:
  ApiGateway:
    Type: 'AWS::Serverless::Api'
    Properties:
      Name: !Join ['-', [!Ref 'AWS::StackName', 'gateway']]
      StageName: dev
  WwddLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: askdonald/
      Runtime: nodejs8.10
      Role: !GetAtt LambdaExecutionRole.Arn
      RestApiId: !Ref ApiGateway
      Events:
        ApiEventSource:
          Type: Api
          Properties:
            Path: /askdonald
            Method: post
        ApiEventSource2:
          Type: Api
          Properties:
            Path: /askdonald
            Method: get
Outputs:
  WebsiteUrl : 
      Description : Click here
      Value:  !Ref DomainNameString